import type { MetadataRoute } from "next";

/**
 * /robots.txt — generated by Next.js from this file.
 * Allows everything for all crawlers, blocks only API + cart UI routes
 * (no SEO value, just server endpoints), and points to the sitemap.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/cart/"],
      },
    ],
    sitemap: "https://airplanestore.fr/sitemap.xml",
    host: "https://airplanestore.fr",
  };
}
